---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_dock: true
dockitems_remove: 
# These seem to be case sensitive??
# Didn't remove "Facetime" but *did* remove "FaceTime"...
- Launchpad
- TV
- Podcasts
- 'App Store'
- Safari
- Mail
- Maps
- Photos
- FaceTime
- Calendar
- Contacts
- Reminders
- Notes
- Freeform
- Music
- News
- 'System Settings'
- 'iPhone Mirroring'

dockitems_persist:
# 1 is finder (default as of writing, hopefully stays that way)

# 2 is the Terminal app of choice
- name: "Warp"
  path: "/Applications/Warp.app"
  pos: 2

# Browser
- name: "Microsoft Edge"
  path: "/Applications/Microsoft Edge.app"
  pos: 3

# Code Editor
- name: "Sublime Text"
  path: "/Applications/Sublime Text.app/"
  pos: 4

# VSCode as a fallback if Sublime isn't working or I don't care for it
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app"
  pos: 5

# Hi, internet friends!
- name: "Discord"
  path: "/Applications/Discord.app"
  pos: 6

# Notes, notes, and more notes
- name: "Obsidian"
  path: "/Applications/Obsidian.app"
  pos: 7

# I'm the only user and I want to be prompted for my password with each Sudo invoke
configure_sudoers: false

dotfiles_repo: https://github.com/droidforensics/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_repo_version: master # Geerling's branch is `master` and my fork took it by default
dotfiles_files:
  - .zshrc # Made some changes from Geerling's
  - .gitignore # Reasonable defaults from Geerling
  - .inputrc # Reasonable defaults from Geerling
  - .osx # Made changes from Geerling's
  - .vimrc # Geerling's seem reasonable, I don't use vim much, but trying to learn
  # TODO: Wonder if I need my starship.toml file?
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - curl
  - git
  - gh # GitHub Command Line Tool
  - go
  - ssh-copy-id
  - openssl
  - wget
  - zsh-history-substring-search
  - rustup # Rust installer (and version handler?)
  - starship
  - vim
  - nano
  # - tailscale # Doesn't seem to want to install? Super minor problem tho.

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - microsoft-edge
  - google-chrome
  - sublime-text
  - visual-studio-code
  - discord
  - obsidian
  - citrix-workspace # As much as I'd prefer not, having work accessible is probably good
  - font-jetbrains-mono-nerd-font
  - warp
  - anaconda # Easy Python package/env management available @ work, want to get used to @ home.

osx_script: "~/.osx --no-restart"

configure_sublime: true
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-mdl" # Markdown Lint
  - "SublimeLinter-annotations" # TODO and FIXME support
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2" # Geerling's preferred theme
  - "Predawn" # Theme - Seems pretty good
  - "Materialize" # Theme - Many options
  - "TrailingSpaces"
  - "WordingStatus"